Basic/highcastle01/basic2/BOJ_10093.cpp, Basic/highcastle01/basic2/BOJ_10804.cpp, Basic/highcastle01/basic2/BOJ_1267.cpp, Basic/highcastle01/basic2/BOJ_15552.cpp, Basic/highcastle01/basic2/BOJ_2309.cpp, Basic/highcastle01/basic2/BOJ_2439.cpp, Basic/highcastle01/basic2/BOJ_2440.cpp, Basic/highcastle01/basic2/BOJ_2441.cpp, Basic/highcastle01/basic2/BOJ_2442.cpp, Basic/highcastle01/basic2/BOJ_2443.cpp, Basic/highcastle01/basic2/BOJ_2444.cpp, Basic/highcastle01/basic2/BOJ_2445.cpp, Basic/highcastle01/basic2/BOJ_2446.cpp, Basic/highcastle01/basic2/BOJ_2562.cpp
=> basic_1week_2

Intermediate/chlwndks33/Binary Search/10815.cpp, Intermediate/chlwndks33/Binary Search/10816.cpp, Intermediate/chlwndks33/Binary Search/16401.cpp, Intermediate/chlwndks33/Binary Search/1654.cpp, Intermediate/chlwndks33/Binary Search/1822.cpp, Intermediate/chlwndks33/Binary Search/18869.cpp, Intermediate/chlwndks33/Binary Search/18870.cpp, Intermediate/chlwndks33/Binary Search/1920.cpp, Intermediate/chlwndks33/Binary Search/2110.cpp, Intermediate/chlwndks33/Binary Search/2295.cpp, Intermediate/chlwndks33/Binary Search/2467.cpp, Intermediate/chlwndks33/Binary Search/2473.cpp, Intermediate/chlwndks33/Binary Search/2805.cpp, Intermediate/chlwndks33/Binary Search/3151.cpp, Intermediate/chlwndks33/Binary Search/7453.cpp, Intermediate/chlwndks33/TwoPointer/13144.cpp, Intermediate/chlwndks33/TwoPointer/1644.cpp, Intermediate/chlwndks33/TwoPointer/1806.cpp, Intermediate/chlwndks33/TwoPointer/2003.cpp, Intermediate/chlwndks33/TwoPointer/2230.cpp
=> Pull request

Basic/hodu26/Array/10807.cpp, Basic/hodu26/Array/10808.cpp, Basic/hodu26/Array/11328.cpp, Basic/hodu26/Array/13300.cpp, Basic/hodu26/Array/1475.cpp, Basic/hodu26/Array/1919.cpp, Basic/hodu26/Array/2577.cpp, Basic/hodu26/Array/3273.cpp, Basic/hodu26/Linked_List/1158.cpp, Basic/hodu26/Linked_List/1406.cpp, Basic/hodu26/Linked_List/5397.cpp, Basic/hodu26/Linked_List/practice_1.cpp
=> Basic_week2

Intermediate/chlwndks33/TwoPointer/20922.cpp, Intermediate/chlwndks33/TwoPointer/22862.cpp, Intermediate/chlwndks33/TwoPointer/2531.cpp
=> TwoPointer problem

Basic/rlathdns/Array/Boj_1475.cpp, rlathdns/Array/2577.cpp
Reverts alps-jbnu/23ALPStudy#89
=> Revert "Revert "zz""

Intermediate/chlwndks33/Binary Search/2110.cpp, Intermediate/chlwndks33/DP/1003.cpp, Intermediate/chlwndks33/DP/10844.cpp, Intermediate/chlwndks33/DP/11053.cpp, Intermediate/chlwndks33/DP/11055.cpp, Intermediate/chlwndks33/DP/1149.cpp, Intermediate/chlwndks33/DP/11659.cpp, Intermediate/chlwndks33/DP/11726.cpp, Intermediate/chlwndks33/DP/11727.cpp, Intermediate/chlwndks33/DP/11852.cpp, Intermediate/chlwndks33/DP/14501.cpp, Intermediate/chlwndks33/DP/1463.cpp, Intermediate/chlwndks33/DP/15486.cpp, Intermediate/chlwndks33/DP/1912.cpp, Intermediate/chlwndks33/DP/1932.cpp, Intermediate/chlwndks33/DP/2193.cpp, Intermediate/chlwndks33/DP/2579.cpp, Intermediate/chlwndks33/DP/9095.cpp, Intermediate/chlwndks33/DP/9461.cpp
=> Week-02 Study

Exercise/zszszszs/3week/.cph/.d.cpp_db22a3fe352223bb6d0205e11868057c.prob, Exercise/zszszszs/3week/HW2/.cph/.23559(밥).cpp_02872bc61a219e7a479d45c71db60b72.prob, Exercise/zszszszs/3week/HW2/.cph/.2616.cpp_0c2def57269a2ef377a42737fb0f2cd6.prob, Exercise/zszszszs/3week/HW2/17398.cpp, Exercise/zszszszs/3week/HW2/19326.cpp, Exercise/zszszszs/3week/HW2/23559.cpp, Exercise/zszszszs/3week/HW2/2616.cpp, Exercise/zszszszs/3week/d.cpp
1. 엠티 춤 준비
2. 원형스택 구현 및 문제 만들기 
3. HCI 과제
4. 과로사 해서 죽음
안하길 뭘 안해~~~
이정현 특) 막상 야망 엠티가서 잘 못놀아서 학과 엠티 그리워함~
=> 김지성 요번주 특)

Exercise/alphasobs/week_3/exercise/16948.cpp, Exercise/alphasobs/week_3/exercise/19949.cpp, Exercise/alphasobs/week_3/exercise/2785.cpp, Exercise/alphasobs/week_3/exercise/7573.cpp, Exercise/alphasobs/week_3/homework/23559.cpp, Exercise/alphasobs/week_3/homework/2616.cpp
=> why error occured

Intermediate/chlwndks33/DP/10942.cpp, Intermediate/chlwndks33/DP/1699.cpp, Intermediate/chlwndks33/DP/9084.cpp, Intermediate/chlwndks33/DP/9251.cpp
=> Week 2 Study

Basic/hodu26/Stack/10773.cpp, Basic/hodu26/Stack/10828.cpp, Basic/hodu26/Stack/17298.cpp, Basic/hodu26/Stack/1874.cpp, Basic/hodu26/Stack/2493.cpp, Basic/hodu26/Stack/6198.cpp
=> Basic_Week3

Exercise/alphasobs/week_4/homework/15559.cpp, Exercise/alphasobs/week_4/homework/15685.cpp, Exercise/alphasobs/week_4/homework/19951.cpp
=> 4/3 00:30 뉴캐슬 vs 맨유

Intermediate/chlwndks33/Greedy/1026.cpp, Intermediate/chlwndks33/Greedy/11399.cpp, Intermediate/chlwndks33/Greedy/11501.cpp, Intermediate/chlwndks33/Greedy/1541.cpp, Intermediate/chlwndks33/Greedy/1744.cpp, Intermediate/chlwndks33/Greedy/1931.cpp, Intermediate/chlwndks33/Greedy/2170.cpp, Intermediate/chlwndks33/Greedy/2217.cpp, Intermediate/chlwndks33/Greedy/2457.cpp
=> Week 3 study

Basic/hodu26/BFS/1697.cpp, Basic/hodu26/BFS/1926.cpp, Basic/hodu26/BFS/2178.cpp, Basic/hodu26/BFS/4179.cpp, Basic/hodu26/BFS/7576.cpp, Basic/hodu26/Deque/1021.cpp, Basic/hodu26/Deque/10866.cpp, Basic/hodu26/Deque/11003.cpp, Basic/hodu26/Deque/5430.cpp, Basic/hodu26/Queue/10845.cpp, Basic/hodu26/Queue/18258.cpp, Basic/hodu26/Queue/2164.cpp
=> Basic_week4

Intermediate/chlwndks33/DAC/2339.cpp
=> Add 2339.cpp

Basic/hodu26/BFS/10026.cpp, Basic/hodu26/BFS/1012.cpp, Basic/hodu26/BFS/13549.cpp, Basic/hodu26/BFS/1600.cpp, Basic/hodu26/BFS/2146.cpp, Basic/hodu26/BFS/2206.cpp, Basic/hodu26/BFS/2468.cpp, Basic/hodu26/BFS/2573.cpp, Basic/hodu26/BFS/2583.cpp, Basic/hodu26/BFS/2667.cpp, Basic/hodu26/BFS/5014.cpp, Basic/hodu26/BFS/5427.cpp, Basic/hodu26/BFS/6593.cpp, Basic/hodu26/BFS/7562.cpp, Basic/hodu26/BFS/7569.cpp, Basic/hodu26/BFS/9466.cpp, Basic/hodu26/Graph/11403.cpp, Basic/hodu26/Graph/11724.cpp, Basic/hodu26/Graph/1260.cpp, Basic/hodu26/Graph/1707.cpp, Basic/hodu26/Graph/2606.cpp, Basic/hodu26/Graph/2660.cpp, Basic/hodu26/Graph/5567.cpp
=> Basic_Bfs1_Graph1

Basic/LuckyPlace/recursion/BOJ_1074.cpp, Basic/LuckyPlace/recursion/BOJ_11729.cpp, Basic/LuckyPlace/recursion/BOJ_1629.cpp, Basic/LuckyPlace/recursion/BOJ_17478.cpp, Basic/LuckyPlace/recursion/BOJ_1780.cpp, Basic/LuckyPlace/recursion/BOJ_1992.cpp, Basic/LuckyPlace/recursion/BOJ_2448.cpp, Basic/LuckyPlace/recursion/BOJ_2630.cpp
=> add recursion

Intermediate/chlwndks33/Dijkstra/1261.cpp, Intermediate/chlwndks33/Dijkstra/17835.cpp, Intermediate/chlwndks33/Dijkstra/20183.cpp
=> Dijkstra - pr

Basic/hodu26/Graph/1043.cpp, Basic/hodu26/Graph/2617.cpp, Basic/hodu26/Recursion/1074.cpp, Basic/hodu26/Recursion/11729.cpp, Basic/hodu26/Recursion/1629.cpp, Basic/hodu26/Recursion/17478.cpp, Basic/hodu26/Recursion/1780.cpp, Basic/hodu26/Recursion/1992.cpp, Basic/hodu26/Recursion/2630.cpp
=> Basic_Graph2_Recursion1

Intermediate/chlwndks33/TopologicalSort/1005.cpp, Intermediate/chlwndks33/TopologicalSort/1766.cpp, Intermediate/chlwndks33/TopologicalSort/2056.cpp, Intermediate/chlwndks33/TopologicalSort/21276.cpp, Intermediate/chlwndks33/TopologicalSort/2252.cpp, Intermediate/chlwndks33/TopologicalSort/2623.cpp, Intermediate/chlwndks33/TopologicalSort/2637.cpp
=> TopologicalSort-PR

Basic/hodu26/BackTracking/15650.cpp, Basic/hodu26/BackTracking/15651.cpp, Basic/hodu26/BackTracking/15652.cpp, Basic/hodu26/BackTracking/15654.cpp, Basic/hodu26/BackTracking/15655.cpp, Basic/hodu26/BackTracking/15656.cpp, Basic/hodu26/BackTracking/15657.cpp, Basic/hodu26/BackTracking/15663.cpp, Basic/hodu26/BackTracking/15664.cpp, Basic/hodu26/BackTracking/15665.cpp, Basic/hodu26/BackTracking/15666.cpp, Basic/hodu26/BackTracking/6603.cpp, Basic/hodu26/Tree/11725.cpp, Basic/hodu26/Tree/1991.cpp
=> Basic_BackTracking2 & Tree1

Basic/highcastle01/BFS/BOJ_13549.cpp, Basic/highcastle01/BST/BOJ_21939.cpp, Basic/highcastle01/BST/BOJ_7662.cpp, Basic/highcastle01/Heap/BOJ_11279.cpp, Basic/highcastle01/Heap/BOJ_1655.cpp, Basic/highcastle01/Heap/BOJ_1927.cpp, Basic/highcastle01/Heap/BOJ_2075.cpp, Basic/highcastle01/Recursion/BOJ_17478.cpp, Basic/highcastle01/Recursion/BOJ_1992.cpp
=> Basic_7week2
